name: CI

on:
  push:
    branches: [main]        
  pull_request:             
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .      
          pip install -r dev-requirements.txt


      - name: Run unit tests
        env:
          OPENAI_API_KEY: dummy-key
        run: pytest -q

